##version: '3.6'
##
##services:
##  products-backend:
##    container_name: backend
##    build: ./
##    command:
##      - php -S 127.0.0.1:8080
##    working_dir: /products
##    ports:
##      - "8080:8080"
##
##    environment:
##      DB_CONNECTION: mysql
##      DB_HOST: codelyticaleg.com:3306
##      DB_PORT: 3306
##      DB_DATABASE: admin_mostafa
##      DB_USERNAME: omar_grad
##      DB_PASSWORD: Reem*01019965508
##
##    volumes:
##      - ./:/products
##
##
##version: "3.6"
##services:
##  webserver:
##    build: ./
##
##    ports:
##      - "80:80"
##      - "443:443"
##    volumes:
##      - ./:/var/www/html
##    environment:
##      MYSQL_DB_CONNECTION: test
##      MYSQL_DB_NAME: test
##      MYSQL_USER: test
##      MYSQL_PASSWORD: test
##      SITE_URL: http://localhost
##    networks:
##      - test
##
##networks:
##  test:
##    external: true
#version: '3.1'
#
#services:
#  php:
#    container_name: php_apache
#    depends_on:
#      - db
#    build:
#      context: .
#    ports:
#      - "80:80"
#    restart: always
#    volumes:
#      - ./:/var/www/html/products
#      - ./.htaccess:/var/www/html/products/.htaccess
#    dns:
#      - 8.8.8.8
#      - 4.4.4.4
#      - 192.168.9.45
#
#  db:
#    image: couchbase:community-6.6.0
#    container_name: couchbase_server
#    deploy:
#      replicas: 1
#    volumes:
#      - ~/couchbase/node1:/opt/couchbase/var
#    ports:
#      - 8091:8091
#      - 8092:8092
#      - 8093:8093
#      - 8094:8094
#      - 11210:11210
#
#  phpmyadmin:
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 8080:80
#    environment:
#      - PMA_ARBITRARY=1




#version: '3.6'
#services:
#
#  www:
#
#    image: php:8.1.1-apache
#    volumes:
#      - "./:/var/www/html"
#    ports:
#      - 80:80
#      - 443:443
#    networks:
#      - lamp-docker
#    working_dir: /var/www/html
#    domainname: local
#    extra_hosts:
#      - "lara.local:127.0.0.1"
#
#networks:
#  lamp-docker:
#    driver: bridge

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: lamp_demo
      MYSQL_USER: lamp_demo
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
  www:
    depends_on:
      - db
    image: php:8.1.1-apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge
